### ISSUE TITLE
Getting the following error when trying to link the lastest version of nuget package in Xamarin.iOS

### ISSUE THREAD

**Issue by sameertotey** [AzureAD/azure-activedirectory-library-for-dotnet#1059]
**I am using nuget package version 3.19.6** 

When I try to build my app, I get the following error:
MTOUCH : error MT2002: Failed to resolve "Microsoft.IdentityModel.Clients.ActiveDirectory.ClientAssertionCertificate" reference from "Microsoft.IdentityModel.Clients.ActiveDirectory, Version=3.17.2.31801, Culture=neutral, PublicKeyToken=31bf3856ad364e35"
    --- inner exception

I only get this error if I enable linking while trying to build the app.  I do not get this error when linking is turned off.  I did not have this issue with 3.19.4

**Comment by jennyf19** [comment]
@sameertotey 
This is because you are trying to access a method which has been marked as [obsolete](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/blob/dev/adal/src/Microsoft.IdentityModel.Clients.ActiveDirectory/AuthenticationContext.cs#L757) for public clients. Xamarin only supports public clients, and since version [3.17.1](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/releases/tag/v3.17.1) of the library, we have marked the methods that should not be used on public clients as obsolete for security purposes. 

Confidential client applications typically run on servers and are considered difficult to access, and therefore capable of keeping an application secret. A web app is the most common confidential client. Each client has a distinct configuration, and the client secret is passed only in the back channel and never directly exposed.

A public client application typically runs on devices or desktop machines. They are not trusted to keep application secrets. They are unable to hold runtime secrets, so, as a result, they have no client secret. 

If you are using Xamarin, you will want to acquire a token using one of the [public client application flows](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/Acquiring-tokens-interactively---Public-client-application-flows).

Also, the latest version of the library is [3.19.6](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/releases/tag/v3.19.6) - I would recommend using this version.

**Comment by sameertotey** [comment]
I am using the public client application flow to obtain the token using ADAL.  I am not referencing the ClientAssertionCertificate in my app.  It is the linker that is having this problem. Thanks

**Comment by jennyf19** [comment]
@sameertotey 
I see...thanks for clarifying. 
Can you try with the latest version of the library? Linked above. thanks

**Comment by sameertotey** [comment]
The linking problem is happening with 3.19.6.   Everything was fine when I was using 3.19.4. The only way I can build my app with 3.19.6 is to turn linking off, however this increases the size of my app (ipa file).  I will try this with the sample app (Dir-SearchClient) active-directory-dotnet-native-multitarget

**Comment by jennyf19** [comment]
@sameertotey Glad you got it figured out...thanks for the update.

**Comment by sameertotey** [comment]
Opened an issue with Microsoft.Azure.ServiceBus because it now has a dependency on Microsoft.Azure.Services.AppAuthentication which is causing the issue.
https://github.com/Azure/azure-service-bus-dotnet/issues/472
