### ISSUE TITLE
Redirect after Login does not work as expected. (Vue App)

### ISSUE THREAD

**Issue by HofmT** [AzureAD/azure-activedirectory-library-for-dotnet#1071]
Hello,

I have a Vue App with Webpack that I want to secure with ADAL. My Vue App has a separate Log-In page to initiate the login process with Azure AD. After a successful login I want the user to be redirected to the root index ('/').
In order to achieve that I set my _redirectUri_ to _http://127.0.0.1:8081/_ and also set the config variable _navigateToLoginRequestUrl_ to false.

Now what happens after a login is that I do get redirected to the root index however the page ist completely blank. There is no error but the content of the site is simply not loaded.

Does anyone have an idea how to approach this issue? Does it have something to do with Webpack or with Adal?

I appreciate any help. Thank you!

Kind regards
Tobias

**Comment by jmprieur** [comment]
Hello @HofmT : are you using ADAL.NET in the backend ? I'm not familiar with Vue, and thought is was for JavaScript. 
- Would it be a question for [ADAL.js](https://github.com/AzureAD/azure-activedirectory-library-for-Dotnet) ?
- Otherwise if this is for ADAL.NET, can you please share a simple repro?

**Comment by HofmT** [comment]
@jmprieur I am sorry. You're right I am using ADAL.js. Sorry for the confusion.
