### ISSUE TITLE
Documentation needed for Adal exception UnknownUserType

### ISSUE THREAD

**Issue by pregress** [AzureAD/azure-activedirectory-library-for-dotnet#1159]
Is it possible to provide more information on the [page](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/Exceptions-in-ADAL.NET) about UnknownUserType?

We receive this error on random times, for random users. We don't know where to look when we receive this error. Or what is causing the error.
These users could sign in before, and can sign in again after some time. I think this is caused by AD on premise sync with Azure AD.

Also see: https://stackoverflow.com/questions/51630959/adfs-authentication-failed-unknow-user-type for more information

**Comment by jmprieur** [comment]
Thanks for your feedback, @prebenh 
We've updated the conceptual documentation's page with the following:

"this error happens when, in non-interactive flows (resource owner password credentials grant), ADAL.NET is not able to identify whether the user is a federated or managed (which is needed in order to know where to send the credentials). Managed users are user of an Azure AD tenant. Federated users are managed by another authority than Azure AD."

If you look at the logs with PII (See [New way of logging, controlling PII (ADAL.Net > 3.18)](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/Logging-in-ADAL.Net#new-way-of-logging-controlling-pii-adalnet--318) ), they state the username and the account type found in the discovery response, which can help you understanding the isse

**Comment by jmprieur** [comment]
Closing as fixed.

**Comment by pregress** [comment]
Thanks for the info !
