### ISSUE TITLE
PlatformParamters can't be instantiated in order to disable embedded Webview

### ISSUE THREAD

**Issue by TruthWithLove** [AzureAD/azure-activedirectory-library-for-dotnet#1245]
**Which Version of ADAL are you using ?**
 4.0.0. - Preview

**Which platform has the issue?**
Xamarin, iOS

**What authentication flow has the issue?**
* Desktop 
    * [ ] Interactive
    * [ ] WIA
    * [ ] U/P
    * [ ] Device code flow (browserless)
    *[x] Mobile
 
 
Other? - please describe;
 This property is public, but not visible to my application. Could it have something to do with CLRCompliant attribute is false, and Xamarin's usage of .NET?

**Expected behavior**
I should be able to create the object below
https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/blob/dev/adal/src/Microsoft.IdentityModel.Clients.ActiveDirectory/Platforms/iOS/PlatformParameters.cs

**Actual behavior**
The object isn't available, as if it's private

**Possible Solution**
CLRAttribute?

**Comment by jmprieur** [comment]
@ZeroPKI : 
ADAL.NET only supports embedded web view. MSAL.NET supports [both](https://aka.ms/msal-net-uses-web-browser) embedded web view and system web browser. 

what is your scenrio? why would you want to use the sytem browser with ADAL? is it an option for you to move to MSAL.NET?

**Comment by TruthWithLove** [comment]
@jmprieur 
Does MSAL support ADFS? I read that ADAL is the only way to go for this. 
ZeroPKI depends on claims offered via federation, graph, or claims offered through an ADFS trust.  

If ADFS connectivity is a requirement, should I be using ADAL?

**Comment by jmprieur** [comment]
@ZeroPKI 
no it does not support ADFS yet. Are you interested in a direct ADFS connection? or through a federation (which is something that will come quicker)

If direct ADFS connection is a requirement (and you don't need to sign-in with MFA), yes, you should use ADAL.

**Comment by bgavrilMS** [comment]
@ZeroPKI -  Apart from what Jean-Marc is saying, i.e. system web browser is not supported on msal ...

I think what is happening is that you are writing your code in the .netstandard shared assembly of the xamarin app. What we've done is to define PlatformParameters for each target platform. In case of netstandard, the platform parameters are empty, because there is no commonality between iOS, Android and UWP between them. 

So the thing to do is to call the PlatformParameters constructor from the actual iOS / Android / UWP assemblies, not from the shared one. You can use Xamarin's Dependecy Service to inject the object back into the shared component. 

https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/dependency-service/

Let me know if this makes sense and if you think a sample would be useful.

**Comment by TruthWithLove** [comment]
Yes, a short sample or description would be helpful Thank you @bgavrilMS
