### ISSUE TITLE
Login doesn't show in Xamarin.GTK

### ISSUE THREAD

**Issue by PostImpatica** [AzureAD/azure-activedirectory-library-for-dotnet#1262]
**Which Version of ADAL are you using ?**
ADAL 3.19.8

**Which platform has the issue?**
Xamarin forms project using Authentication within a dependency service inside a native GTK project 

_Xamarin Forms Project_
`Xamarin.Forms 3.1.0.637273`
_GTK Native Project_
`.Net 4.7.1`
`GTK v3.1.0.637273`

**What authentication flow has the issue?**
* [x ] Mobile

**Repro**

```csharp
[assembly: Dependency(typeof(ProTrain.GTK.DependencyServices.Authenticator))]
namespace ProTrain.GTK.DependencyServices
{
    class Authenticator : IAuthenticator
    {
        AuthenticationContext authContext;
        public void PrepareForLogout()
        {
            authContext.TokenCache.Clear();
        }
        public async Task<AuthenticationResult> Authenticate(string authority, string resource, string clientId, string returnUri)
        {
            authContext = new AuthenticationContext(authority);

            if (authContext.TokenCache.ReadItems().Any())
                authContext = new AuthenticationContext(authContext.TokenCache.ReadItems().First().Authority);

            var uri = new Uri(returnUri);
            var platformParams = new PlatformParameters(PromptBehavior.Auto, false);
            var authResult = await authContext.AcquireTokenAsync(resource, clientId, uri, platformParams);
            return authResult;
        }
    }
}
```

**Expected behavior**
The dialog allowing me to login should popup

**Actual behavior**
No dialog is shown and the following line:
`var authResult = await authContext.AcquireTokenAsync(resource, clientId, uri, platformParams);`
throws the following exception:
`{"Invalid owner window type. Expected types are IWin32Window or IntPtr (for window handle)."}`

**Comment by bgavrilMS** [comment]
Hi @helzgate, 

I believe the issue is because you are creating the PlatformParamters from a net desktop assembly. 

The problem is that PlatformParameters is platform dependent, and you need to new it up inside each of the platform dependent assemblies (iOS, Android and UWP). For example, for Android, the actual class that needs to be created is [this one](        https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/blob/dev/adal/src/Microsoft.IdentityModel.Clients.ActiveDirectory/Platforms/android/PlatformParameters.cs). You can see in the constructor that you have to pass an Activity object - this will be used for the window to pop up. Obviously this can't exist on an iOS project. 

I think that because of your GTK, you are constructing the PlatformInformation in a dot net desktop context, ? In any case you have 2 options: 

1. Move the authenticator code in the platform specific assemblies instead of in common OR

2. Move only the PlatformParameters construction in platform specific assemblies. Then inject it back to the common assembly. Xamarin offers a [Dependency Service ](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/dependency-service/) to help with this.

If this indeed the problem, I'd like to hear from you how we could make this more clear - through documentation, or maybe a better sample , or maybe we should try to throw an exception?
