### ISSUE TITLE
Make AcquireTokenAsync cancellable by passing CancellationToken

### ISSUE THREAD

**Issue by marnilss** [AzureAD/azure-activedirectory-library-for-dotnet#1306]
**Is your feature request related to a problem? Please describe.**
When doing broker assisted logins (MS Authenticator) in an App, and the user cancels the login process by pressing Home button on device and then reactivating the App, the App is hung waiting for the AcquireTokenAsync to return.

**Describe the solution you'd like**
Make it possible to pass a CancellationToken in the request to AcquireTokenAsync

**Describe alternatives you've considered**
Alternatively a new method on the AuthenticationContinuationHelper, like AbortBroker(), to cancel the hanging/pending authentication call waiting for broker to reactivate with AuthenticationContinuationHelper.SetBrokerContinuationEventArgs(...).

I have found a workaround on this by crafting a special url like https://dummypath?error=...&error_description=.... and pass it to AuthenticationContinuationHelper.SetBrokerContinuationEventArgs().

**Additional context**
Using broker assisted (SSO) with MS Authenticator and Azure AD with ADAL i iOS app.

**Comment by jmprieur** [comment]
@henrik-me @MarkZuber : I'm thinking that TokenRequest supporting this on MSAL.NET would make a lot of sense. I don't think we'd take it for ADAL.NET, though. Also there is a workaround.

**Comment by MarkZuber** [comment]
I had originally plumbed through a bit more of this when I added cancellationtoken support for device code flow but we held it to keep the change specific to device code for the purpose of that release.  but i agree that we should do this across the board.  the downside is that it will double the number of API surfaces so we don't break back-compat since we can't make CancellationToken.None an optional parameter since it's not compile-time constant.  So perhaps we do this as part of the API simplification process.

**Comment by jmprieur** [comment]
@MarkZuber I was more thinking of doing it with TokenRequest in MSAL.NET (to avoid multiplying the overrides)

**Comment by jmprieur** [comment]
@marnilss : we'll do that in MSAL.NET (not ADAL.NET)

**Comment by jmprieur** [comment]
@marnilss. Thanks for sharing this scenario. Closing this issue for ADAL.NET as we're going to do this in MSAL.NET. The corresponding issue is https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/635
