### ISSUE TITLE
System.Windows.Forms dependency

### ISSUE THREAD

**Issue by ParanoidPenguin** [AzureAD/azure-activedirectory-library-for-dotnet#1341]
Hi! I just upgraded Microsoft.IdentityModel.Clients.ActiveDirectory package from 3.19.8 to 4.3.0 and noticed that it added a reference to System.Windows.Forms to my ASP.net (4.7.1) web project. Is this intended/required? If so then please disregard... it just feels a bit odd.

**Comment by MarkZuber** [comment]
We recently fixed an issue via pull request [1328](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/pull/1328) with UI threading that requires us to post to a Windows Forms control.  So this does bring in this dependency usage with our library on .net framework since the UI/browser controlling code is in the same library.
