### ISSUE TITLE
PlatformParameters not having PromptBehavior for netstandard

### ISSUE THREAD

**Issue by ritchxu** [AzureAD/azure-activedirectory-library-for-dotnet#1484]
We're in the process of convert our project from netfx to netcore, after switching to netstandard, we noticed in contrast to netfx, the library's `PlatformParameters` class doesn't have constructors with control over prompt behavior. Is there a reason for this design?

**Comment by bgavrilMS** [comment]
Hi @ritchxu 

Unfortunately .Net Core does not have any UI libraries, so we cannot show UI. .NetCore 3.0 should bring WinForms / WPF but until then, we cannot host a web browser in a UI panel. 

The approach we are considering is to open the default OS browser instead of the a self hosted one. However, this work will be done in MSAL, our next gen auth library https://github.com/AzureAD/microsoft-authentication-library-for-dotnet

All this being said, why do you need interactive auth from .net core? Do you have a command line application?

**Comment by ritchxu** [comment]
@bgavrilMS you're right, we do have a command line application in which we invoke PowerShell cmdlet to access Azure KeyVault, and that requires us to authenticate. The authentication actually works if we're on corp. network because it leverages the Windows Integrated Authentication. However, problem starts to surface if we are on VPN. Then KeyVault is requesting MFA which needs a UI to interactively authenticate.

**Comment by bgavrilMS** [comment]
Yes, unfortunately we do not have a solution involving ADAL and .Net Core for this. You can get creative and create a .Net Classic process that handles the auth to work around this.

You can use Device Code Flow https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/Device-profile-for-devices-without-web-browsers which is supported on netcore.

We will support this type of scenario from MSAL, which we recommend to switch to. Today on MSAL we support the username password flow - see details https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Username-Password-Authentication. You could revert to this flow instead of interactive auth (it's not recommended, but should be ok as a stop gap).
