### ISSUE TITLE
[Question]Can anyone guide me in the usage of the ClientCredential(String, ISecureClientSecret) option of constructor? 

### ISSUE THREAD

**Issue by AshleyAsh90** [AzureAD/azure-activedirectory-library-for-dotnet#1509]
I know I have to create a class which would implement the ISecureClietSecret interface which has the ApplyTo function which takes an IDictionary of two strings as parameters. But what are these strings supposed to be? What is the purpose of this function that needs to be implemented? I do see that the IDictionary is the  "Dictionary to which the securestring is applied to be sent to server" but i am just unclear as to how to go about this. Could anybody kindly guide me?

**Comment by bgavrilMS** [comment]
Hi @AshleyAsh90 - we can help. 

Do you have a business need to use ADAL? Most development occurs on our next-gen auth library, MSAL - https://github.com/AzureAD/microsoft-authentication-library-for-dotnet 

Otherwise we try to keep the wiki and samples as updated as possible, so have a look there. You should be able to build this from a secure string: 

https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/Client-credential-flows

**Comment by AshleyAsh90** [comment]
Hi @bgavrilMS ,

Thank you for getting back to me. I will take a look at the article.
Yes. We currently are building an interface with Dynamics365, and the Dynamics365 team suggests using ADAL. Please see below. 
[Connect to Dynamics 365 for Customer Engagement web services using OAuth](https://docs.microsoft.com/en-us/dynamics365/customer-engagement/developer/connect-customer-engagement-web-services-using-oauth)
Would you suggest using MSAL instead? If so shouldn't the Dynamics team also be suggesting to use this? We are in early stages of development so if this is the direction Microsoft is headed then I would rather change it now than later. I appreciate your input on this.

**Comment by bgavrilMS** [comment]
Well, since their samples are built around ADAL, you should probably go with it for now, especially as you might want to reach out Dynamics for support at some point. 

MSAL is gaining traction but we cannot move all our customers (internal and external) at once. 

Don't worry though, we have a good upgrade story from ADAL -> MSAL, just make sure you put your auth code behind some interface so you can switch implementations later.
