### ISSUE TITLE
`AADSTS50097: Device authentication is required` error with no explanation

### ISSUE THREAD

**Issue by mjcheetham** [AzureAD/azure-activedirectory-library-for-dotnet#1543]
**Which Version of ADAL are you using ?**
ADAL 3.19.4

**Which platform has the issue?**
net45

**What authentication flow has the issue?**
* Desktop / Mobile
    * [x] Interactive

**Is this a new or existing app?**
b. The app is in production, uses the same version of ADAL, but started seeing this issue

**Repro**

```csharp
var context = new AuthenticationContext(authorityHostUrl, _cache);
var platformParameters = new PlatformParameters(PromptBehavior.SelectAccount);

AuthenticationResult result = await context.AcquireTokenAsync(
    resource,
    clientId,
    redirectUri,
    platformParameters,
    UserIdentifier.AnyUser,
    extraQueryParameters: null);
```

**Expected behavior**
User is prompted to authenticate, enters credentials and an AT is returned.

**Actual behavior**
User is prompted to authenticate, enters credentials and an error is thrown.

**Additional context/ Logs / Screenshots**

The application in question is Git Credential Manager. A customer has started hitting authentication problems with no changes to GCM or the version of ADAL we're using.
The error (below) indicates there's some requirement for the device before authentication will proceed but there is no feedback as to _what_ this is and no way to diagnose or act on the problem.

```
{
  "error": "invalid_grant",
  "error_description": "AADSTS50097: Device authentication is required.\r\nTrace ID: dda59793-3a78-464a-9e38-1b68562b1501\r\nCorrelation ID: 913ada2a-39b1-4399-a45d-30e9ef2bb94d\r\nTimestamp: 2019-03-20 01:18:17Z",
  "error_codes": [
    50097
  ],
  "timestamp": "2019-03-20 01:18:17Z",
  "trace_id": "dda59793-3a78-464a-9e38-1b68562b1501",
  "correlation_id": "913ada2a-39b1-4399-a45d-30e9ef2bb94d"
}
```

See https://github.com/Microsoft/Git-Credential-Manager-for-Windows/issues/843 for more information. The original user has captured a Fiddler trace.

**Comment by mjcheetham** [comment]
Note: This error has been encountered in the past on the ADAL Objective-C library where there was a mismatch in the expected order of challenges from STS when doing 'passwordless auth' (using the authenticator app).

One thing that might be useful is some user actionable remedy in the error messages from the STS or ADAL in these cases.. e.g., "please ensure your device is AAD joined" or "please try username/password authentication" etc.

**Comment by jmprieur** [comment]
Won't fix in ADAL.
We'll do it in MSAL.NET (sub error code for Conditional access)

**Comment by jmprieur** [comment]
This error is due to the fact that the Azure AD tenant admin now requires device authentication. In the case of guest scenarios (B2B) this could be either tenant admin btw.

The mitigation, in that case would be:
-	For the tenant admin to remove the conditional access policy, or not apply it to this specific app.
-	Or to rebuild the application using the latest version of MSAL.NET with the ` .WithBroker(true)` enabled, which will leverage WAM. This sample explains how to do that. This is a relatively simple change to an MSAL application

https://github.com/Azure-Samples/active-directory-xamarin-native-v2/blob/7d0220626b500828c6fe899275985a8ef6f73fdf/2-With-broker/UserDetailsClient/UserDetailsClient/MainPage.xaml.cs#L42-L49
