### ISSUE TITLE
VS UI can hang due to not having proper SynchronizationContext for UI interaction

### ISSUE THREAD

**Issue by MarkZuber** [AzureAD/azure-activedirectory-library-for-dotnet#1548]
**Which Version of ADAL are you using ?**
Note that to get help, you need to run the latest preview or non-preview version
For MSAL, please log issues to https://github.com/AzureAD/microsoft-authentication-library-for-dotnet
ADAL v5.0.0-preview

**Which platform has the issue?**
Windows (net45)

**What authentication flow has the issue?**
* Desktop / Mobile
    * [x] Interactive
    * [ ] Integrated Windows Auth
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web App
    * [ ] Authorization code
    * [ ] OBO
* Web API
    * [ ] OBO

We check internally when starting the windows web authentication dialog that we're running on an MTA or STA thread. Since we're using async await, we'll usually end up here on an MTA thread and try to create a new STA thread to run the browser on. This doesn't work in some cases when the parent window isn't currently pumping messages (like in VS's case) and so the app hangs with a deadlock. We need to capture the synchronization context at acquiretokeninteractive so that we can use the appropriate sync context when creating the interactive browser dialog.

**Comment by MarkZuber** [comment]
https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/pull/1549

**Comment by jennyf19** [comment]
released in [ADAL 5.0.1-preview](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/releases/tag/ADAL-v5.0.1-preview)

**Comment by marnilss** [comment]
Will this also fix the UI hang/block that happens when debugging an UWP application that uses ADAL?

I'm calling AuthenticationContext.AcquireTokenAsync(…) for an interactive user login (showing embedded browser window) from a background task (Task.Run()) and mostly it blocks the application after finishing the login. The browser window is closed, but it never returns from the AcquireTokenAsync method.
Running without debugging works most of the time, but never works while debugging application in VS.

Sounded similar to this issue, so hoping it will get fixed at the same time.

**Comment by MarkZuber** [comment]
@marnilss If you capture the synchronization context from your UI thread and then pass it into AcquireTokenAsync then this should work.

**Comment by bgavrilMS** [comment]
@MarkZuber - I don't believe we expose any mechanism like .WithSyncronizationContext. We just capture the current SyncronizationContext [here](https://github.com:443/AzureAD/microsoft-authentication-library-for-dotnet/blob/bogavril/sf/src/Microsoft.Identity.Client/ApiConfig/AcquireTokenInteractiveParameterBuilder.cs#L88) and try to use it later.

The hang may be because of [this Wait()](https://github.com:443/AzureAD/microsoft-authentication-library-for-dotnet/blob/dev3x/src/Microsoft.Identity.Client/Platforms/net45/WebUI.cs#L86) 

Otherwise, if I understand correctly, we are saying that developers should call AcquireTokenInteractive only from the UI thread so that we can capture its SyncContext ?

**Comment by MarkZuber** [comment]
Yes, apologies.  I didn't remember correctly how we expose this.  AcquireTokenInteractive must be called from the UI thread so we can properly capture its sync context and properly work with the UI.  The WithSynchronizationContext method is internal only and is called within AcquireTokenInteractive

**Comment by marnilss** [comment]
Ok, if AuthenticationContext.AcquireTokenAsync(…) must be called from UI thread, it would be really nice if you could mention that somewhere! I can't find that information in neither XML comments nor wiki. 
I've seen somewhere in source code that you were creating new STA thread for browser so I thought it wasn't necessary to call from UI thread.

We've been running it for a year with Xamarin on iOS and invoking it from non-UI thread without a problem. Only experiencing problem in Windows UWP app.

**Comment by bgavrilMS** [comment]
I'm going to reopen this issue because UWP is different than Net Desktop. We have different code for UWP that does not use SyncronizationContext - here's how we get back to the UI thread: 

https://github.com:443/AzureAD/microsoft-authentication-library-for-dotnet/blob/dev3x/src/Microsoft.Identity.Client/Platforms/uap/WebUI.cs#L76

**Comment by marnilss** [comment]
> Yes, apologies.  I didn't remember correctly how we expose this.  AcquireTokenInteractive must be called from the UI thread so we can properly capture its sync context and properly work with the UI.  The WithSynchronizationContext method is internal only and is called within AcquireTokenInteractive

@MarkZuber , is it certain that you must make call from UI thread? **If so pleeeaase write it somewhere in documentation.** I've looked through the wiki and XML comments, and no mention of it anywhere. 

Saying that a call is interactive is not the same thing - it only implies that some kind of user-interface will be shown. It could be running its own UI-thread without any requirement on the calling thread.
