### ISSUE TITLE
User not prompted to enter credentials when using PromptBehavior.Always

### ISSUE THREAD

**Issue by GPugnet** [AzureAD/azure-activedirectory-library-for-dotnet#165]
Version :3.1.203031538-alpha
 
On WinRT, the AuthenticationContext do not always prompt for credentials when PromptBehavior is set to Always.

I am using the following piece of code : 
var authorizationParameters = new AuthorizationParameters(PromptBehavior.Always, false);
                authenticationResult = await authenticationContext.AcquireTokenAsync(ap.Resource, clientId, redirectUri, authorizationParameters);

**Comment by afshins** [comment]
@GPugnet Could you please explain more? What happens instead of showing the prompt? Do you get a token from the cache or an error? Also, if you can collect ADAL logs and Fiddler traces, that would be helpful. This shows how to get ADAL logs: https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/blob/master/README.md#logs
