### ISSUE TITLE
Restructure NuGet/project package

### ISSUE THREAD

**Issue by onovotny** [AzureAD/azure-activedirectory-library-for-dotnet#419]
My suggestion here is to use the `\ref` / bait-and-switch technique to release a single library instead of needing a PCL  + .Platform package.

The bulk of the impl can be a `netstandard 1.x` library and then platform-specific cross-compiled versions exist in the package that will light-up when used on those platforms.

**Comment by kpanwar** [comment]
netstandard has not GA yet. We cannot move to that model until GA is done.

**Comment by ravensorb** [comment]
I agree -- what would be the advantage of the "bait-and-switch"?

**Comment by kpanwar** [comment]
Most importantly, Xamarin works without any issues. ADAL uses several platform specific features that would require investigation before moving to NetStandard.

**Comment by mhutch** [comment]
Using bait and switch is possible without netstandard.

See http://log.paulbetts.org/the-bait-and-switch-pcl-trick/

**Comment by onovotny** [comment]
One advantage is often simpler code - easier to maintain. You don't have to jump through as many hoops to factor things in two libraries when you can just ifidef things out for the PCL (and throw a not implemented exception). Effectively, the PCL just becomes a reference assembly ala @mhutch's link above.

**Comment by danstiner** [comment]
Another point in favor, we encountered a problem where _a project referencing a project_ using this package would fail at runtime with a TypeInitializationException because the platform specific dll is not copied to the output directory of the referencing project. We expect the bait-and-switch method would resolve this.

Relevant SO post on how msbuild does not bring over references it detects are not used: http://stackoverflow.com/questions/20280717/references-from-class-library-are-not-copied-to-running-project-bin-folder

**Comment by kpanwar** [comment]
http://www.codiply.com/blog/dependency-injection-across-multiple-layers-with-ninject/

This shows why you are seeing the problem. Platform DLL is only used via dependency injection and ends up getting stripped by the linker.
