### ISSUE TITLE
Not able to sign out and sign in as different user

### ISSUE THREAD

**Issue by anand-rengasamy** [AzureAD/azure-activedirectory-library-for-dotnet#58]
I would like to provide a sign out and sign in as different user experience in my app.
In sign out, I am clearing the token cache
Ctx.TokenCacheStore.Clear() And Call 'AcquireTokenAndContinue'.

Since I do not know the user id upfront, I am using the below overload
public void AcquireTokenAndContinue(string resource, string clientId, Uri redirectUri, AuthenticationContextDelegate authDelegate);

Calling AcquireTokenAndContinue return the token for previous user. I don't get any prompt to enter new credentials.

**Comment by Strepto** [comment]
While this is closed I had this issue today and can leave a small how to fix guide:

The problem seems to arise when a user has logged in to another app using an account from a different tenant A, and the app is a single tenant app linked to tenant B. There is no prompt to sign in with the correct account, as the tenant error happens before any password is entered.

For me the fix was to sign in with the account I wanted to use in another non-tenant locked app (I used the Add account in Visual Studio 2019), afterwards this account was used correctly in the sign in process of the app I actually wanted to use.
