### ISSUE TITLE
Unable to use "prompt=admin_consent" as extra query parameter in Xamarin.PCL

### ISSUE THREAD

**Issue by VDanylevskyi** [AzureAD/azure-activedirectory-library-for-dotnet#606]
When I am trying to use following code in Xamarin PCL (Android)
`var PlatformParameter =new PlatformParameters(this);`
`result = await authContext.AcquireTokenAsync(AppIdURI, ClientId, RedirectUri, PlatformParameter, UserIdentifier.AnyUser, "prompt=admin_consent");`

I receive an exception: duplicate query parameter 'prompt' in extraqueryparameters.

I am using this call to add permissions for the application on admin level in a multi tenant scenario.

Maybe someone know how to manage this problem.

Thanks

**Comment by juunas11** [comment]
Seems to be due to this line in PlatformInformationBase.cs: https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/blob/dev/src/ADAL.PCL/Platform/PlatformInformationBase.cs#L65.

It adds `prompt=login` by default and then the token acquiring handler throws an error about the duplicate parameter. Perhaps it could be allowed to override this query parameter?

**Comment by kpanwar** [comment]
We added support for prompt behavior in iOS and android. You should be able to use PromptBehavior.Auto and send admin consent as extra QP
