### ISSUE TITLE
When AcquireToken, ADAL.NET shoud not respond with "Interaction required" when network has high latencies.

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/azure-activedirectory-library-for-dotnet#668]
ADAL.NET is responding "Interaction required" when the network latency (for instance 300ms), instead of returning an exception so that the application can decide if it wants to retry or inform the user.

See the detailed repro steps: 
https://stackoverflow.microsoft.com/questions/46569/microsoft-identitymodel-clients-activedirectory-adalexception-user-interaction

**Comment by KaeTar** [comment]
we are making the call
authresult = await authcontext.AcquireTokenAsync(_clientID, _clientID, new Uri(_redirectUri), new PlatformParameters(PromptBehavior.Never));

The problem is that there seems to be a VERY short timeout 250ms or so that if it does not get a response back from the server it throws an exception saying that interaction is required.   I am actually very surprised that there is not a way to specify the timeout.   We are making this call and wanting it to use integrated authentication and return an error if the authentication fails.   If it fails, we then retry the call with PromptBehavior.Always to display the ui.  I can see where PromptBehavior.Auto would try, timeout quickly and then display the login UI.  However with Auto we see the ui flash most of the time and go away.  This is also a UI black eye.   Can we get a change where we can specify the timeout in milliseconds before the UI is displayed on Auto, and a timeout before it throws an exception on PromptBehavior.Never.

**Comment by jmprieur** [comment]
@kpanwar: what about adding a setting in ADAL.NET so that users can increase the timeout? Or is the STS verifying delays?

**Comment by danieldobalian** [comment]
@jmprieur @kpanwar does this on `AcquireTokenAsync` or also `AcquireTokenSilentAsync`?
