### ISSUE TITLE
Custom Web Proxy

### ISSUE THREAD

**Issue by ywhe** [AzureAD/azure-activedirectory-library-for-dotnet#706]
Hi there,

Seems the ADAL only support  Default Web Proxy currently. But my scenario is that, we need to request access token for different tenant in same process. And we also need to access different tenant via different proxy. 
so, how can i achieve this?

Thanks,

**Comment by jmprieur** [comment]
Please see #552

**Comment by ywhe** [comment]
hi @jmprieur,

Thanks for your quick response. But checked the code, seems the only way is set the default proxy.
` public IWebProxy GetDefaultWebProxy()
        {
            return WebRequest.DefaultWebProxy;
        }`
so, is there any other way to set web proxy via code?

Thanks,

**Comment by mjcheetham** [comment]
Hello @ywhe,

So if I understand correctly, your scenario is that you need to communicate with multiple tenants, where one of them is over a different proxy from the others?

This is unfortunately not supported with the current design of ADAL.NET.

I guess what you'd want is to be able to scope proxy settings per `AuthenticationContext`, and use the different contexts to communicate with different tenants?

Every `HttpClientHandler` instance which is created by [`HttpMessageHandlerFactory`](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/blob/055ae8804e428493abf8ff6b500238a4ca1a5c07/src/ADAL.PCL/Http/HttpMessageHandlerFactory.cs#L42) has the web proxy set to `IWebProxyProvider.GetDefaultProxy()` when they are constructed.

Since the factory here is static it is shared across all `AuthenticationContexts`.

**Comment by ywhe** [comment]
hi @mjcheetham,
Thanks a lot for  your response. yea...i'm trying to change the code for the specific project. 
btw, do you think it's a common requirement? is it possible to expose proxy setting instead of using the default one?

thanks for your help!
