### ISSUE TITLE
AcquireToken with claims doesn't work with PromptBehavior.Auto

### ISSUE THREAD

**Issue by larrxu** [AzureAD/azure-activedirectory-library-for-dotnet#939]
The new Acquire Token with claims API has a regression in UI behavior:
```
authContext.AcquireTokenAsync(parameters.Resource, clientId, redirectUri, new PlatformParameters(PromptBehavior.Auto), new UserIdentifier(parameters.UserId, UserIdentifierType.RequiredDisplayableId), null, "claims");
```
When using the AcquireToken call withOUT claims, the PromptBehavior=Auto works as expected: it only prompts the first time and all following calls will get token silently.
However, when using the call with claims, Auto doesn't work properly and each time the pop-up shows briefly then disappears. We are using the library in SSDT and this is causing the pop-up to keep showing for every SQL connection + background connections which breaks UX.

**Comment by jmprieur** [comment]
This is by design as this override of AcquireTokenAsync does not look at the cache; the Claims parameter is used in the very specific scenario of conditional access. 
- For a public client/native application The idea is that a previous call was successfully made to AcquireTokenAsync, and the access token from the AuthenticationResult was used to access a resource, but this resource realized that it needed more claims  about the user, that is more evidence of his/her identity (for instance it needed the user to do two factor authentication). At that moment, ADAL.NET throws an AdalClaimChallengeException, which contains a Claims property. The client application must then call again AcquireTokenAsync passing as a Claim parameter the value of the Claims property from the AdalClaimChallengeException.. Since the token was not containing this claim, it makes complete sense to bypass the cache, and force the acquisition of the token whatever the value of the promptBehavior. 
- For a web API (confidential client application) in the case of the Service to service call on behalf of the user AdalClaimChallengeException is thrown by ADAL.Net in case the called Web API requires more claims from the user (for instance 2-factors authentication). The Claims member contain some json fragment with the claims which are expected. The calling web api needs to surface this claim back to the public client application calling it one way or another, so that this one can call AcquireTokenAsync with the right claims. Again we are back in the previous case except that this time the call to the first Web API returns an HTTP 403 (ADAL is not involved in this as this happens when the resource is accessed)
More details are provided in the [Developer Guidance for Azure Active Directory Conditional Access](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-conditional-access-developer). It’s also illustrated in the [active-directory-dotnet-webapi-onbehalfof-ca](https://github.com/Azure-Samples/active-directory-dotnet-webapi-onbehalfof-ca) sample (See the [AccessCaApiController.cs lines 92 to 96](https://github.com/Azure-Samples/active-directory-dotnet-webapi-onbehalfof-ca/blob/master/TodoListService/Controllers/AccessCaApiController.cs#L92-L96))
