### ISSUE TITLE
Distinguish between 'AnyUser' and 'UnknownUser' with regards to cache

### ISSUE THREAD

**Issue by afshins** [AzureAD/azure-activedirectory-library-for-dotnet#98]
We need to distinguish between ‘I don’t care’ and ‘I don’t know’ when it comes to user. Currently, when UserAssertion is created without explicit user in On Behalf Of scenario, we assume it means ‘AnyUser’ and match it with any user we find in the cache. However, there is a user in the assertion that we don’t know as we cannot look inside that assertion. In this case, we can say ‘we don’t know’ the user and do not match any token from the cache. This reduces cache usage, but can avoid such confusions. The good news is that this is not an interactive flow, so the change in behavior does not lead to more user involvement.

**Comment by dstrockis** [comment]
@jelledruyts @afshins  Could ADAL accept a UniqueId in the UserAssertion constructor and perform cache lookup based on UniqueId? Or more likely accept a UserIdentiferType in the constructor?

ADAL can't look inside the user assertion, but in the On Behalf Of scenario, the audience of the token can definitely parse the token as pass ADAL the user's ObjectId, for instance.

We discussed this briefly in the past, and I believe @RandalliLama had some opposition. Can't remember.

**Comment by dstrockis** [comment]
@vibronet too for good measure.

**Comment by jelledruyts** [comment]
I think it would make more sense to base the cache lookup on the UniqueId if present (and not return anything if there's no explicit match i.e. the UnknownUser vs AnyUser idea). Currently it matches on DisplayableId which seems weak.

But as I've learnt in the mean time the token cache should be per-user anyway (not shared across multiple users), so for me the issue is far less important now.
